version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/set_version.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 60
      runas: root
