version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install fastapi uvicorn pytest

  build:
    commands:
      - pytest

artifacts:
  files:
    - '**/*'
