version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - pytest
      - echo "APP_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION" > version.txt

artifacts:
  files:
    - '**/*'
